[versions]
hec-monolith = "5.0.0-rc06"
jooq-codegen = "24.12.04-2025.01.21"
jooq = { strictly = "3.18.7-jdk11" }
cwms-data-api = "10.1.0"

service-annotations = "2.0.1"

jdom = "1.1.3"

junit = "5.9.1"
testcontainers = { strictly = "2.0.2"}
ojdbc = "19.3.0.0"
cwms-testcontainers = "2.0.0"

[libraries]
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
hec-monolith-bom = { module = "mil.army.usace.hec:hec-monolith-bom", version.ref = "hec-monolith" }
cwms-db-jooq-codegen = {module = 'mil.army.usace.hec:cwms-db-jooq-codegen_java11', version.ref = "jooq-codegen" }
jooq = {module = 'org.jooq.pro-java-11:jooq', version.ref = "jooq" }

cwms-http-client = { module = "mil.army.usace.hec:cwms-http-client", version.ref = "cwms-data-api" }
cwms-data-api-client = { module = "mil.army.usace.hec:cwms-data-api-client", version.ref = "cwms-data-api" }
cwms-data-api-model = { module = "mil.army.usace.hec:cwms-data-api-model", version.ref = "cwms-data-api" }

service-annotations = { module = "mil.army.usace.hec:service-annotations", version.ref = "service-annotations" }

jdom = { module = "org.jdom:jdom", version.ref = "jdom"}

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit"}
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit"}
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit"}

ojdbc = { module = "com.oracle.database.jdbc:ojdbc8", version.ref = "ojdbc" }

testcontainers-testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers"}
testcontainers-jdbc = { module = "org.testcontainers:testcontainers-jdbc", version.ref = "testcontainers"}
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers"}
testcontainers-cwms = { module = "mil.army.usace.hec:testcontainers-cwms", version.ref = "cwms-testcontainers"}

[bundles]
junit-api = ["junit-api", "junit-params"]


