[versions]
hec-monolith = "4.0.0-RC3"

service-annotations = "1.2.2"

jdom = "1.1.3"

junit = "5.9.1"

[libraries]
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
hec-rmi = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }

service-annotations = { module = "mil.army.usace.hec:service-annotations", version.ref = "service-annotations" }

jdom = { module = "org.jdom:jdom", version.ref = "jdom"}

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit"}
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit"}
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit"}

[bundles]
junit-api = ["junit-api", "junit-params"]


